version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: (cd centos && docker build -t bbyars/mountebank-centos:latest .)
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker push bbyars/mountebank-centos:latest

